// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Prefer NEXT_PUBLIC env vars for client-side access, fall back to server-side names if present.
const SUPABASE_URL = process.env.NEXT_PUBLIC_SUPABASE_URL ?? process.env.NEXT_SUPABASE_URL ?? '';
const SUPABASE_PUBLISHABLE_KEY = process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY ?? process.env.NEXT_SUPABASE_PUBLISHABLE_KEY ?? '';
console.log("supabase url", SUPABASE_URL);
if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  // Helpful warning during development when env vars are missing or not exposed to the browser
  // (e.g. missing NEXT_PUBLIC_ prefix).
  // In production you should ensure these env vars are set.
  // Use NEXT_PUBLIC_SUPABASE_URL and NEXT_PUBLIC_SUPABASE_ANON_KEY for client-side usage.
  // For server-side usage, use secure keys (e.g. service role) and keep them out of the client.
  // eslint-disable-next-line no-console
  console.warn(
    'Supabase env variables missing: set NEXT_PUBLIC_SUPABASE_URL and NEXT_PUBLIC_SUPABASE_ANON_KEY (or NEXT_SUPABASE_URL and NEXT_SUPABASE_PUBLISHABLE_KEY)'
  );
}

// Avoid accessing window / localStorage on the server
const isBrowser = typeof window !== 'undefined';

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: isBrowser ? window.localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  },
});

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";